### ISSUE TITLE
Update to TShock 4.3.13 (Rest api changed)

### ISSUE THREAD

**Issue by bippity** [popstarfreas/Rest-Inventory#7]
They changed some more REST endpoints to v2, such as token creation.

https://github.com/popstarfreas/Rest-Inventory/blob/master/index.php#L72
https://github.com/popstarfreas/Rest-Inventory/blob/master/index.php#L96
Should now be something like `$response = json_decode(@file_get_contents("http://$location/v2/token/create?username=$rest_user&password=$rest_pass", 0, $ctx));`

I'm probably missing something (or screwed up my own code) because the token doesn't seem to get destroyed and while it displays the player list, it also says "Server failed to respond"

**Comment by popstarfreas** [comment]
Other people keep saying that. I don't know why because I have a minorly modified version of the code that accesses 4 different servers and I don't have token destroy issues.

**Comment by popstarfreas** [comment]
Commit [898b50](https://github.com/popstarfreas/Rest-Inventory/commit/898b50df78a03e8394d4dd2b224d4a8a3fd91378) now fixes both issues.
